name: 'Build Image and Trigger Staging Deployment'
description: 'A reusable action to build a Docker image and trigger a staging deployment.'
branding:
  icon: 'package'
  color: 'orange'

inputs:
  token:
    description: 'The GitHub token to use for checkout.'
    required: true
  image-url:
    description: 'The URL of the Docker image.'
    required: true
  gcloud-credentials:
    description: 'The Google Cloud credentials JSON.'
    required: true

runs:
  using: 'composite'
  steps:

    # Checkout with submodules
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ inputs.token }}

    # Authenticate with Google Cloud
    - uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.gcloud-credentials }}

    # Login to Docker
    - name: Login to Docker
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev
      shell: bash

    # Build image
    - name: Build image
      run: |
        export SHORT_SHA=${GITHUB_SHA:0:7}
        docker pull ${{ inputs.image-url }} || true
        docker build --cache-from ${{ inputs.image-url }}:latest --tag ${{ inputs.image-url }}:$SHORT_SHA .
        docker image tag ${{ inputs.image-url }}:$SHORT_SHA ${{ inputs.image-url }}:latest
      shell: bash

    # Push image
    - name: Push image
      run: |
        export SHORT_SHA=${GITHUB_SHA:0:7}
        docker push ${{ inputs.image-url }}:$SHORT_SHA
      shell: bash