# .github/workflows/app-build-reusable.yml (in AngleProtocol/github-workflows repository)

name: Build and update staging (Reusable)

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: 'The name of the app.'
      image-url:
        required: true
        type: string
        description: 'The URL of the Docker image.'
      gcloud-credentials:
        required: true
        type: string
        description: 'The Google Cloud credentials JSON.'

    secrets:
      GITHUB_TOKEN:
        required: true
      GCLOUD_CREDENTIALS:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build Image with Composite Action
        uses: AngleProtocol/github-workflows/.github/actions/app-build.yml@main
        with:
          app: ${{ inputs.app }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-url: ${{ inputs.image-url }}
          gcloud-credentials: ${{ inputs.gcloud-credentials }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}