# .github/workflows/app-build-reusable.yml (in AngleProtocol/github-workflows repository)

name: Build and update staging (Reusable)

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: 'The name of the app.'
      image-url:
        required: true
        type: string
        description: 'The URL of the Docker image.'
      gcloud-credentials:
        required: true
        type: string
        description: 'The Google Cloud credentials JSON.'
      token:
        description: 'The GitHub token to use for checkout.'
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build Image with Composite Action
        uses: ./.github/actions/app-build.yml@main
        with:
          app: ${{ inputs.app }}
          token: ${{ inputs.token }}
          image-url: ${{ inputs.image-url }}
          gcloud-credentials: ${{ inputs.gcloud-credentials }}